### ISSUE TITLE
Clarify statement "JSON is not a hypermedia"

### ISSUE THREAD

**Issue by elliottinvent** [bigskysoftware/hypermedia-systems#40]
In [What is a Hypermedia System](https://hypermedia.systems/book/hypermedia-systems/#_what_is_a_hypermedia_system) it says:

> Unfortunately, today, you probably associate the term "REST" with JSON APIs, since that is where the term is typically used in industry. This is a misapplied use of the term REST because **JSON is not a hypermedia**, which is an explicit requirement for a system to be considered "REST-ful." 

(emphasis mine)

But earlier you refer to [HAL](https://github.com/mikekelly/hal_specification/blob/master/hal_specification.md) (which comes in `hal+json` form) as a Hypermedia:
> Not everyone abandoned hypermedia, of course. There have been heroic efforts to continue to advance hypermedia outside of HTML, efforts like HyTime, VoiceXML, and HAL.

I'd suggest that it's not the language (data serialisation / markup) that makes it not a hypermedia, but the absence of hypermedia controls, to quote earlier in the book:

> what makes a hypermedia a hypermedia is the presence of hypermedia controls, that is, elements in the hypermedia that allow users to select non-linear actions within the hypermedia

**Comment by codetalcott** [comment]
maybe: "JSON is not itself a hypermedia" or "JSON alone is not a hypermedia."

**Comment by elliottinvent** [comment]
For sure, a plain JSON object is not a hypermedia format, so I think both of those statements are correct. However, I think there's some confusion around what you could do within a JSON object to make it a hypermedia (if anything). 

For example:

1. adding a hypermedia control (e.g. a `href` using the URI of another object)
2. adding multiple hypermedia controls so that it enables "non-linear branching"
3. having a client that makes it human-friendly *

* taken from a @1cg Discord comment from earlier today:
> the trick (and this took me a long time to appreciate) is that you need a hypermedia client as well [...] building a client like a browser that respects the uniform interface of a hypermedia API and is also not a terrible experience for a human user appears to be really, really hard to me

Option 1 would make a basic webpage not a valid Hypermedia response:
```
<html>
  <h1>Hello World</h1>
</html>
```

Option 2 would make the example above _and_ https://example.com/ not a valid Hypermedia response.

Option 3 is a really interesting one but seems pretty subjective.

One for @1cg to weigh in on I think. 

For me, this isn't necessarily about the sentence in the book which could perhaps be easily fixed like this:

> ... This is a misapplied use of the term REST because a typical JSON API response is not a hypermedia

It's more a point of intrigue.

**Comment by 1cg** [comment]
I have been using the terminology: "JSON is not a *natural* hypermedia because it does not include hypermedia controls."

This is like XML not being a hypermedia: you can impose hypermedia controls on top of that format, which is what Hyperview does, but XML itself is not a natural hypermedia.

I'm not sure if this terminology makes any sense, but that's the way I try to phrase things when I can remember.

**Comment by elliottinvent** [comment]
I like this analogy and think it makes a ton of sense. So for it to be a _natural hypermedia_, it needs hypermedia controls baked into the [data serialisation/markup] language itself?

**Comment by 1cg** [comment]
yep, that's the distinguishing characteristic of a hypermedia (IMO): the presence of native hypermedia controls

A side note: I've recently come to the realization that the hypermedia client is also crucial to the functioning of a hypermedia system, which is why just slapping hypermedia controls on top of JSON or XML isn't enough.  Building a hypermedia client that understands those hypermedia controls and can present them to a human is a huge task, and something usually glossed over in discussions of JSON-as-REST.

This is why Hyperview is such an interesting technology: @adamstep provides a working hypermedia client, not just a hypermedia format built on top of XML.  That makes Hyperview a much more complete hypermedia system with which to build mobile hypermedia-based applications.

**Comment by elliottinvent** [comment]
I've proposed a fix for this in #26, specifically: https://github.com/bigskysoftware/hypermedia-systems/pull/26/commits/e4813c9fb3d5639e574daf7bb4b107ecb8c2c946
