### ISSUE TITLE
Edit check: meaning the same?

### ISSUE THREAD

**Issue by codetalcott** [bigskysoftware/hypermedia-systems#47]
"The content _within_ the form is more important than the content within an anchor tag."
Suggest changing to:
"The content _within_ the form does different work than the content within an anchor tag."

**Comment by elliottinvent** [comment]
I think this is an improvement. 

As a suggestion it might make sense to clarify what is doing the work, it's not the content itself but the client (the web browser):

"The content within the form causes the client to do different work than the content within an anchor tag."

**Comment by netaisllc** [comment]
@codetalcott  @elliottinvent I agree with where you're going, but it isn't the _content_ that causes the browser behavior, is it?.  Rather it is the fact that the content in question is enclosed by the `form` tag.

Something like this:  "Because the content is enclosed in a `form` tag, it's handled differently by the browser than content enclosed in an `a` tag."

**Comment by 1cg** [comment]
The content within the form is more important, but that content itself isn't a hypermedia control.

Maybe:

> The content within a form alters the hypermedia interaction with the server by adding information to the HTTP request that the form generates
